custom/urls.py
from django.urls    import path
from .views         import *

app_name = 'custom'
urlpatterns = [
    path('registration/login/', RegistrationLoginView.as_view(), name='login'),
    path('registration/reservation/', RegistrationReservationView.as_view(), name='reservation'),
    path('registration/guest_list/', RegistrationGuestListView.as_view(), name='guest_list'),
    path('registration/detail/<str:encrypted_id>/', RegistrationDetailView.as_view(), name='detail'),
    path('registration/main_guest/', RegistrationMainGuestView.as_view(), name='main_guest'),
    path('registration/other_info/', RegistrationOtherInfoView.as_view(), name='other_info'),
]

guest_facing/check_out/urls.py
from django.urls    import path
from .views         import IndexView, CheckOutDataView, CheckOutLoginView, CheckOutBillView, CheckOutCompleteView

app_name = 'check_out'
urlpatterns = [
    path('check_out/', IndexView.as_view(), name='index'),
    path('check_out/data/', CheckOutDataView.as_view(), name='data'),
    path('check_out/login/', CheckOutLoginView.as_view(), name='login'),
    path('check_out/bill/<str:reservation_no>', CheckOutBillView.as_view(), name='bill'),
    path('check_out/complete/', CheckOutCompleteView.as_view(), name='complete'),
]

hotel_guest/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.views.i18n import JavaScriptCatalog

urlpatterns = [
    path('', include('guest_facing.registration.urls')),
    path('', include('guest_facing.check_out.urls')),
    path('', include('guest_facing.chat.urls')),
    path('', include('guest_facing.core.urls')),
    
    path('admin/', admin.site.urls),
    path('i18n/', include('django.conf.urls.i18n')),
    path('jsi18n/', JavaScriptCatalog.as_view(), name='javascript-catalog'),
]

sc_guest/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.views.i18n import JavaScriptCatalog

urlpatterns = [
    path('guest/', include('custom.urls')),
    path('guest/', include('guest_facing.registration.urls')),
    path('guest/', include('guest_facing.check_out.urls')),
    path('guest/', include('guest_facing.chat.urls')),
    path('guest/', include('guest_facing.core.urls')),
    
    path('guest/admin/', admin.site.urls),
    path('guest/i18n/', include('django.conf.urls.i18n')),
    path('guest/jsi18n/', JavaScriptCatalog.as_view(), name='javascript-catalog'),
]

guest_facing/check_out/forms.py
from django                     import forms
from django.conf                import settings
from django.utils.translation   import gettext, gettext_lazy as _
from captcha                    import fields as captchaField, widgets as captchaWidget
from guest_facing.core          import gateways


class CheckOutLoginForm(forms.Form):
    reservation_no  = forms.CharField(label=_('Reservation Number'), required=False)
    last_name       = forms.CharField(label=_('Last Name'), required=False)
    room_no         = forms.CharField(label=_('Room Number'))

    def __init__(self, request, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.request = request
        self.label_suffix = ''
        self.response = {}
        self.fields['reservation_no'].initial = self.request.session.get('check_out', {}).get('preload', {}).get('reservation_no')
        self.fields['last_name'].initial = self.request.session.get('check_out', {}).get('preload', {}).get('last_name')
        self.fields['room_no'].initial = self.request.session.get('check_out', {}).get('preload', {}).get('room_no')
        # add `recaptcha` when not auto login
        if not self.request.session.get('check_out', {}).get('preload', {}).get('auto_login', 0):
            self.fields['recaptcha'] = captchaField.ReCaptchaField(widget=captchaWidget.ReCaptchaV2Invisible)

    def clean(self):
        super().clean()
        reservation_no = self.cleaned_data.get('reservation_no')
        last_name = self.cleaned_data.get('last_name')
        room_no = self.cleaned_data.get('room_no')
        recaptcha = self.cleaned_data.get('recaptcha')

        # validate required field
        if not reservation_no and not last_name:
            self._errors['reservation_no'] = self.error_class([_('Enter the required information')])
            self._errors['last_name'] = self.error_class([_('Enter the required information')])
        if not room_no:
            self._errors['room_no'] = self.error_class([_('Enter the required information')])
        # validate `recaptcha` when not auto login
        if not self.request.session.get('check_out', {}).get('preload', {}).get('auto_login', 0) and not recaptcha:
            self._errors[forms.forms.NON_FIELD_ERRORS] = self.error_class(['recaptcha'])
        # validate to backend
        if not self.errors:
            response = self.gateway_post()
            if response.get('statusCode', '') != '5011':
                self._errors[forms.forms.NON_FIELD_ERRORS] = self.error_class([response.get('status_code', 0)])
        return self.cleaned_data

    def gateway_post(self):
        data = {}
        data['reservationNo'] = self.cleaned_data.get('reservation_no', None)
        data['lastName'] = self.cleaned_data.get('last_name', None)
        data['roomNo'] = self.cleaned_data.get('room_no')
        self.response = gateways.guest_endpoint('post', '/signInCheckOut', self.request.session.get('property_id', ''), data)
        return self.response
    
    def save(self):
        data = self.response
        preload_data = dict(self.request.session.get('check_out', {}).get('preload', {})) # get and store preload because session will be cleared
        self.request.session['check_out'] = {} # clear session data
        self.request.session['check_out']['preload'] = preload_data # restore preload data
        self.request.session['check_out']['bookings'] = data.get('data', {}).get('data', [])
        self.request.session['check_out']['bills'] = data.get('data', {}).get('data', [])
        self.request.session['check_out']['input_reservation_no'] = self.cleaned_data.get('reservation_no')
        self.request.session['check_out']['input_last_name'] = self.cleaned_data.get('last_name')
        self.request.session['check_out']['input_room_no'] = self.cleaned_data.get('room_no')
        if 'preload' in self.request.session['check_out'] and 'auto_login' in self.request.session['check_out']['preload']:
            self.request.session['check_out']['preload']['auto_login'] = 0 # set auto login to False


class CheckOutBillForm(forms.Form):
    reservation_no  = forms.ChoiceField(label=_('Reservation Number'))

    def __init__(self, instance, request, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.instance = instance
        self.request = request
        self.label_suffix = ''
        # populate choices
        self.fields['reservation_no'].choices = []
        for reservation in self.request.session['check_out'].get('bills', []):
            self.fields['reservation_no'].choices.append((reservation.get('pmsNo', ''), reservation.get('firstName', '') + ' ' + reservation.get('lastName', '')))
        # set initial
        self.fields['reservation_no'].initial = self.instance.get('id', '')

    def clean(self):
        super().clean()
        reservation_no = self.cleaned_data.get('reservation_no', '')
        
        if not reservation_no:
            self._errors['reservation_no'] = self.error_class([_('Enter the required information')])
        return self.cleaned_data

    def gateway_post(self):
        reservation_info = self.instance.get('reservationInfo', [])
        data = {'reservationInfo': reservation_info}
        return gateways.guest_endpoint('post', '/postCheckOut', self.request.session.get('property_id', ''), data)

    def save(self):
        response = self.gateway_post()
        if response.get('statusCode', '') == '5013':
            # get existing reservation from backend
            if response.get('reservationNoLeft', []):
                new_guest_data = {}
                new_guest_data['reservationNo'] = next(iter(response.get('reservationNoLeft', [])), '')
                new_guest_data['lastName'] = ''
                new_guest_data['roomNo'] = self.request.session['check_out'].get('input_room_no')
                new_guest_response = gateways.guest_endpoint('post', '/signInCheckOut', self.request.session.get('property_id', ''), new_guest_data)
                self.request.session['check_out']['bills'] = new_guest_response.get('data', {}).get('data', [])
                if not new_guest_response.get('data', {}).get('data', []):
                    self.request.session['check_out']['complete'] = True
            else:
                self.request.session['check_out']['complete'] = True
        else:
            self._errors[forms.forms.NON_FIELD_ERRORS] = self.error_class([response.get('message', _('Unknown error'))])
        return self.instance

guest_facing/check_out/views.py
from django.conf                import settings
from django.contrib             import messages
from django.http                import Http404
from django.shortcuts           import render, redirect
from django.utils               import translation
from django.utils.translation   import gettext, gettext_lazy as _
from django.views.generic       import *
from guest_facing.core          import gateways
from guest_facing.core.views    import IndexView
from guest_facing.core.mixins   import PropertyRequiredMixin, RequestFormKwargsMixin, MobileTemplateMixin
from .forms                     import CheckOutLoginForm, CheckOutBillForm
from .mixins                    import BillRequiredAndExistMixin


class IndexView(IndexView):
    pattern_name = 'check_out:data'


class CheckOutDataView(RedirectView):
    pattern_name = 'check_out:login'

    def get(self, request, *args, **kwargs):
        request.session['property_id'] = request.GET.get('property', None)
        request.session['app'] = request.GET.get('app', 0)
        request.session['check_out'] = {'preload': {}}
        if 'lang' in request.GET: request.session[translation.LANGUAGE_SESSION_KEY] = request.GET.get('lang', 'en')
        if 'auto_login' in request.GET: request.session['check_out']['preload']['auto_login'] = request.GET.get('auto_login', 0)
        if 'reservation_no' in request.GET: request.session['check_out']['preload']['reservation_no'] = request.GET.get('reservation_no', '')
        if 'last_name' in request.GET: request.session['check_out']['preload']['last_name'] = request.GET.get('last_name', '')
        if 'room_no' in request.GET: request.session['check_out']['preload']['room_no'] = request.GET.get('room_no', '')
        return super().get(request, *args, **kwargs)


class CheckOutLoginView(PropertyRequiredMixin, RequestFormKwargsMixin, MobileTemplateMixin, FormView):
    template_name           = 'check_out/desktop/login.html'
    mobile_template_name    = 'check_out/mobile/login.html'
    form_class              = CheckOutLoginForm
    success_url             = '/guest/check_out/bill/{reservation_no}'

    def dispatch(self, request, *args, **kwargs):
        if request.session.get('check_out', {}).get('preload', {}).get('auto_login', 0):
            data = {}
            data['reservation_no'] = request.session.get('check_out', {}).get('preload', {}).get('reservation_no', '')
            data['last_name'] = request.session.get('check_out', {}).get('preload', {}).get('last_name', '')
            data['room_no'] = request.session.get('check_out', {}).get('preload', {}).get('room_no', '')
            form = self.get_form_class()
            form = form(request, data)
            if form.is_valid():
                return self.form_valid(form)
            else:
                return self.form_invalid(form)
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)

    def get_success_url(self):
        if not self.success_url:
            return super().get_success_url()
        reservation = next(iter(self.request.session['check_out'].get('bills', [])), {})
        url = self.success_url.format(**{'reservation_no': reservation.get('pmsNo', '')})
        return url

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        form = context.get('form', None)
        if self.request.session.get('app', 0) and self.request.session.get('check_out', {}).get('preload', {}).get('last_name', '') and (form and not form.is_bound):
            context['skip_last_name'] = True
        return context


class CheckOutBillView(BillRequiredAndExistMixin, PropertyRequiredMixin, RequestFormKwargsMixin, UpdateView):
    template_name           = 'check_out/desktop/bill.html'
    form_class              = CheckOutBillForm
    success_url             = '/guest/check_out/bill/all'

    def gateway_get(self, reservations_no):
        data = {'pmsNos': reservations_no}
        return gateways.guest_endpoint('post', '/billCheckOut', self.request.session.get('property_id', ''), data)

    def get_object(self, queryset=None):
        reservation_no = self.kwargs.get('reservation_no', None)
        reservations_no = [reservation_no]
        if reservation_no == 'all':
            reservations_no = [resv['pmsNo'] for resv in self.request.session['check_out'].get('bills', []) if resv.get('pmsNo', '')]
        response = self.gateway_get(reservations_no)
        obj = response.get('data', {}).get('data', {})
        obj['id'] = reservation_no # set `reservation_no` as unique identifier
        obj['show_bill'] = False if response.get('statusCode', '') == '6004' else True
        return obj

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['gst_no'] = settings.GST_NO
        context['business_no'] = settings.BUSINESS_NO
        context['currency_symbol'] = settings.CURRENCY_SYMBOL
        return context

    def form_valid(self, form):
        data = super().form_valid(form)
        if self.request.session['check_out'].get('complete', None):
            messages.add_message(self.request, messages.SUCCESS, _("All Guests have been successfully checked out.\n\nWe hope you enjoy your stay with us, and we'll see you again soon!"))
        else:
            # reservation = next((temp for temp in self.object.get('reservationInfo') if temp.get('pmsNo', '') == self.object.get('id', None)), {})
            # guest_name = reservation.get('firstName', '') +' '+ reservation.get('lastName', '')
            # guests_left = [temp.get('firstName', '') +' '+ temp.get('lastName', '') for temp in self.request.session['check_out'].get('bills', [])]
            # names_left = '\n- '.join(guests_left)
            #messages.add_message(self.request, messages.SUCCESS, _('We have checked-out the guest:\n- %(name)s\n\nOther guests left to check-out:\n- %(names_left)s') % {'name': guest_name, 'names_left': names_left})
            messages.add_message(self.request, messages.ERROR, _("Can't set in checked out status. End date should be less or equal today!"))
        return data

    def get_success_url(self):
        url = self.success_url
        if len(self.request.session['check_out'].get('bills', [])) == 1: # redirect to last bill if left 1 bill to check-out
            bill = next(iter(self.request.session['check_out'].get('bills', [])), None)
            url = '/guest/check_out/bill/%(reservation_no)s' % {'reservation_no': bill.get('pmsNo', 'all')}
        else:
            url = '/guest/check_out/complete'
        return url


class CheckOutCompleteView(TemplateView):
    template_name           = 'check_out/desktop/complete.html'

    def dispatch(self, request, *args, **kwargs):
        if not request.session.get('check_out', {}).get('complete', None):
            return redirect('check_out:login')
        return super().dispatch(request, *args, **kwargs)

guest_facing/check_out/templates/check_out/mobile/base_mobile.html
{% extends 'check_out/base.html' %}
{% load i18n %}
{% load static %}

{% block static_css %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'check_out/scss/mobile/base_mobile.scss' %}" type="text/x-scss" media="screen">
{% endblock static_css %}

{% block static_js %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'check_out/js/mobile/base_mobile.js' %}"></script>
{% endblock static_js %}

guest_facing/check_out/templates/check_out/mobile/login.html
{% extends 'check_out/mobile/base_mobile.html' %}
{% load i18n %}
{% load static %}
{% load widget_tweaks %}

{% block static_css %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'check_out/scss/mobile/login.scss' %}" type="text/x-scss" media="screen">
{% endblock static_css %}

{% block header_left %}
    <button type="button" class="btn btn-link" id="btn-back" {% if not skip_last_name %}style="display: none;"{% endif %}>
        <i class="fas fa-arrow-left"></i>
    </button>
    {% if not request.session.app %}
        <a href="{% url 'check_out:index' %}" class="btn btn-link" id="btn-home" {% if skip_last_name %}style="display: none;"{% endif %}>
            <img src="{% static 'img/place.svg' %}" />
        </a>
    {% endif %}
    {{ block.super }}
{% endblock header_left %}

{% block content %}
    {{ block.super }}
    <form method="post" id="form-mobile-login" autocomplete="off">
        {% csrf_token %}
        {% render_field form.recaptcha %}
        <div class="row page-header">
            <div class="col-12 text-center">
                <span id="header-reservation-no" class="header-description {% if not skip_reservation_no %}active{% endif %}">{% blocktrans %}Please enter your<br>Reservation Number{% endblocktrans %}</span>
                <span id="header-last-name" class="header-description {% if skip_reservation_no %}active{% endif %}">{% blocktrans %}Please enter your<br>Last Name{% endblocktrans %}</span>
                <span id="header-room-no" class="header-description {% if skip_last_name %}active{% endif %}">{% blocktrans %}Please enter your<br>Room Number{% endblocktrans %}</span>
            </div>
        </div>
        <div class="row page-subheader">
            <div class="col-12 px-0 text-center text-secondary">
                <span id="subheader-reservation-no" class="subheader-description {% if not skip_reservation_no %}active{% endif %}">{% blocktrans %}To begin the online check-out process,<br>please enter your reservation number.{% endblocktrans %}</span>
                <span id="subheader-last-name" class="subheader-description {% if skip_reservation_no %}active{% endif %}">{% blocktrans %}To begin the online check-out process,<br>please enter your last name.{% endblocktrans %}</span>
                <span id="subheader-room-no" class="subheader-description {% if skip_last_name %}active{% endif %}">{% blocktrans %}The following information is required for<br>verification.{% endblocktrans %}</span>
            </div>
        </div>
        <div class="row page-content">
            <div class="col-12 d-flex justify-content-center">
                <div id="content-reservation-no" class="content-input {% if not skip_reservation_no %}active{% endif %}">
                    <div class="md-form input-center input-boxed my-0">
                        {% trans 'Reservation Number' as reservation_number_placeholder %}
                        {% render_field form.reservation_no class="form-control" placeholder=reservation_number_placeholder %}
                    </div>
                </div>
                <div id="content-last-name" class="content-input {% if skip_reservation_no %}active{% endif %}">
                    <div class="md-form input-center input-boxed my-0">
                        {% trans 'Last Name' as last_name_placeholder %}
                        {% render_field form.last_name class="form-control" placeholder=last_name_placeholder %}
                    </div>
                </div>
                <div id="content-room-no" class="content-input {% if skip_last_name %}active{% endif %}">
                    <div class="md-form input-center input-boxed my-0">
                        {% trans 'Room Number' as room_no_placeholder %}
                        {% render_field form.room_no class="form-control" placeholder=room_no_placeholder %}
                    </div>
                </div>
            </div>
        </div>
        <div class="row page-footer">
            <div class="col-12 d-flex justify-content-center">
                <div id="footer-reservation-no" class="footer-button {% if not skip_reservation_no %}active{% endif %}">
                    <button type="button" class="btn btn-primary btn-round m-0" disabled>{% trans 'Next' %}</button>
                </div>
                <div id="footer-last-name" class="footer-button {% if skip_reservation_no %}active{% endif %}">
                    <button type="button" class="btn btn-primary btn-round m-0" disabled>{% trans 'Next' %}</button>
                </div>
                <div id="footer-room-no" class="footer-button {% if skip_last_name %}active{% endif %}">
                    <button type="submit" class="btn btn-primary btn-round m-0" disabled>{% trans 'Next' %}</button>
                </div>
            </div>
        </div>
    </form>
{% endblock content %}

{% block wrapper %}
    {{ block.super }}
    <!-- Error Modal -->
    {% for error in form.non_field_errors %}
        <div class="modal fade auto-show" id="form-error-modal-{{ forloop.counter0 }}" data-backdrop="static" data-keyboard="false" tabindex="-1" role="dialog" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered modal-sm">
                <div class="modal-content">
                    <div class="modal-header bg-primary text-white">
                        <h4 class="modal-title mx-auto">
                            {% if error == '6001' %}
                                {% trans 'checkout_login:error_modal_title:6001' %}
                            {% elif error == 'recaptcha' %}
                                {% trans 'Invalid Input' %}
                            {% else %}
                                {% trans 'checkout_login:error_modal_title:other' %}
                            {% endif %}
                        </h4>
                    </div>
                    <div class="modal-body">
                        {% if error == '6001' %}
                            {% trans 'checkout_login:error_modal_body:6001' %}
                        {% elif error == 'recaptcha' %}
                            {% trans 'Failed to validate reCaptcha' %}
                        {% else %}
                            {% trans 'checkout_login:error_modal_body:other' %}
                        {% endif %}
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-primary mx-auto" data-dismiss="modal">{% trans 'OK' %}</button>
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
{% endblock wrapper %}

{% block static_js %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'check_out/js/mobile/login.js' %}"></script>
{% endblock static_js %}